spring:
  application:
    name: aiprocessor
  main:
    allow-bean-definition-overriding: true

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3
          temperature: 0.7
    vectorstore:
#      pgvector:
#      index-type: HNSW
#      distance-type: COSINE_DISTANCE
#      dimension: 1536
      weaviate:
        host: localhost:8081
